// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWSOaSkezf_yeFRFWMv2STSV2mBA3N5MQ',
    appId: '1:929559084297:web:8cdb20bf58de2086fde7d8',
    messagingSenderId: '929559084297',
    projectId: 'enjoy-b49ea',
    authDomain: 'enjoy-b49ea.firebaseapp.com',
    storageBucket: 'enjoy-b49ea.firebasestorage.app',
    measurementId: 'G-72EN24MHH2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkdaqJTbDBro0GN0jxXygYmJHCsjNhj_k',
    appId: '1:929559084297:android:90babfbe0c6a0be5fde7d8',
    messagingSenderId: '929559084297',
    projectId: 'enjoy-b49ea',
    storageBucket: 'enjoy-b49ea.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqrL2opuk-Jkx_my9Pu5Weijt_m4AIKVU',
    appId: '1:929559084297:ios:c92929134d06e745fde7d8',
    messagingSenderId: '929559084297',
    projectId: 'enjoy-b49ea',
    storageBucket: 'enjoy-b49ea.firebasestorage.app',
    iosBundleId: 'com.example.enjoy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqrL2opuk-Jkx_my9Pu5Weijt_m4AIKVU',
    appId: '1:929559084297:ios:bedcb7edf24281a6fde7d8',
    messagingSenderId: '929559084297',
    projectId: 'enjoy-b49ea',
    storageBucket: 'enjoy-b49ea.firebasestorage.app',
    iosBundleId: 'com.enjoy.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAWSOaSkezf_yeFRFWMv2STSV2mBA3N5MQ',
    appId: '1:929559084297:web:f4abe0cab371762ffde7d8',
    messagingSenderId: '929559084297',
    projectId: 'enjoy-b49ea',
    authDomain: 'enjoy-b49ea.firebaseapp.com',
    storageBucket: 'enjoy-b49ea.firebasestorage.app',
    measurementId: 'G-96NRQ4YB67',
  );
}